export interface AutocompleteItem {
  termo_amigavel: string;
  grupo: number;
  categoria_subcategoria: string;
  codigo_ibama: string;
  classe_perigo_nbr: string;
}

export const AUTOCOMPLETE_DICTIONARY: AutocompleteItem[] = [
  // --- GRUPO 1 ---
  { termo_amigavel: "Farelo de soja", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de soja", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "DDG/DDGS (grãos de destilaria)", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farelo de trigo", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farelo de arroz", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farelo de algodão", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Torta de girassol", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Torta de dendê", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Torta de mamona", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Torta de pinhão manso", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Bagaço de cana-de-açúcar", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Palha de cana-de-açúcar", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Vinhaça concentrada", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Melaço de cana", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Torta de filtro de cana", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Levedura seca de cana/cervejaria", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de arroz", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de café", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Borra de café industrial", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de amendoim", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de cacau", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Casca de açaí", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Bagaço de laranja/cítricos", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Bagaço de maçã", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Bagaço de uva (vinificação)", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Manipueira", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Massa de mandioca residual", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farinha de carne e ossos", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farinha de sangue", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farinha de penas", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Farinha de peixe", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Sebo bovino", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Sebo suíno", grupo: 1, categoria_subcategoria: "Agroindústria e Alimentos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  
  { termo_amigavel: "Casca de eucalipto", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Serragem limpa (não contaminada)", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Resíduo de palma de dendê", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Cavaco de madeira limpo", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Serragem limpa de serraria", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Maravalha", grupo: 1, categoria_subcategoria: "Silvicultura e Madeira Limpa", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  
  { termo_amigavel: "Retalhos de algodão", grupo: 1, categoria_subcategoria: "Têxtil e Vestuário Limpo", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Retalhos de jeans", grupo: 1, categoria_subcategoria: "Têxtil e Vestuário Limpo", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Retalhos de tecido sintético", grupo: 1, categoria_subcategoria: "Têxtil e Vestuário Limpo", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Fibras recicláveis de têxtil", grupo: 1, categoria_subcategoria: "Têxtil e Vestuário Limpo", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Resíduos de confecção pós-consumo", grupo: 1, categoria_subcategoria: "Têxtil e Vestuário Limpo", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  
  { termo_amigavel: "Glicerina bruta (biodiesel)", grupo: 1, categoria_subcategoria: "Química Orgânica e Processos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Óleo fúsel", grupo: 1, categoria_subcategoria: "Química Orgânica e Processos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Flegmaça", grupo: 1, categoria_subcategoria: "Química Orgânica e Processos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Óleo vegetal residual (OGR)", grupo: 1, categoria_subcategoria: "Química Orgânica e Processos", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  
  { termo_amigavel: "Cavaco de ferro/aço", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Cavaco de alumínio", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Cavaco de cobre", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de PEAD", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de PEBD", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de PP", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de PET", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de PVC", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de ABS", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Aparas de poliestireno (PS)", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Plásticos de engenharia off-spec", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Óleo vegetal usado (cozinha)", grupo: 1, categoria_subcategoria: "Metalurgia, Moldagem e Plásticos (Commodities de Reciclagem)", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  
  { termo_amigavel: "Big bag usado (limpo)", grupo: 1, categoria_subcategoria: "Logística e Embalagens Limpas", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },
  { termo_amigavel: "Bombona PEAD azul (limpa)", grupo: 1, categoria_subcategoria: "Logística e Embalagens Limpas", codigo_ibama: "Dispensado", classe_perigo_nbr: "Classe N/A (Coproduto)" },

  // --- GRUPO 2 ---
  { termo_amigavel: "Estéril de mina", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "01 01 01", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Rejeito de minério de ferro", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "01 01 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Lama de caulim", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "01 01 10", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Resíduos de britagem", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "01 04 01", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Rejeito de grafita", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "01 01 11", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Calcário fino/dolomítico", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "06 01 13", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Escória de alto-forno", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "10 01 01", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Escória de aciaria", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "10 01 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Carepa de laminação", grupo: 2, categoria_subcategoria: "Mineração e Siderurgia", codigo_ibama: "10 01 04", classe_perigo_nbr: "Classe II-B" },
  
  { termo_amigavel: "Polímeros fora de especificação", grupo: 2, categoria_subcategoria: "Processamento Mecânico e Manufatura", codigo_ibama: "07 01 06", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Outros resíduos de moldagem", grupo: 2, categoria_subcategoria: "Processamento Mecânico e Manufatura", codigo_ibama: "12 99 99", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Saco de ráfia usado", grupo: 2, categoria_subcategoria: "Processamento Mecânico e Manufatura", codigo_ibama: "15 01 09", classe_perigo_nbr: "Classe II-B" },
  
  { termo_amigavel: "Concreto estrutural britado", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 01 01", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Argamassa de cimento", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 01 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Tijolos e telhas cerâmicas", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 01 03", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Blocos de concreto", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 01 04", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Plástico de embalagem de obra", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 02 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Metal de armação", grupo: 2, categoria_subcategoria: "Construção Civil (RCC Classe A e B Inertes)", codigo_ibama: "17 02 04", classe_perigo_nbr: "Classe II-B" },
  
  { termo_amigavel: "Pneus inservíveis picados", grupo: 2, categoria_subcategoria: "Logística Reversa e Massa Urbana Coletada", codigo_ibama: "16 01 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Cabos elétricos limpos", grupo: 2, categoria_subcategoria: "Logística Reversa e Massa Urbana Coletada", codigo_ibama: "16 02 02", classe_perigo_nbr: "Classe II-B" },
  { termo_amigavel: "Pneus inservíveis inteiros", grupo: 2, categoria_subcategoria: "Logística Reversa e Massa Urbana Coletada", codigo_ibama: "20 04 01", classe_perigo_nbr: "Classe II-B" },

  // --- GRUPO 3 ---
  { termo_amigavel: "Rejeito de fosfato", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 03", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de manganês", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 04", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de cobre", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 05", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de níquel", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 06", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de nióbio", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 08", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de terras raras", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 12", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Rejeito de potássio", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 03 07", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros rejeitos de mineração não especificados", grupo: 3, categoria_subcategoria: "Mineração Extrativa de não metálicos", codigo_ibama: "01 01 99", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Esterco bovino", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 28", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Esterco suíno", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 29", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Cama de frango", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 30", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Soro de leite líquido", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 37", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Casca de ovo", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 38", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos de abate - conteúdo ruminal", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 39", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos de pescado - vísceras", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 40", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos agrossilvopastoris não especificados", grupo: 3, categoria_subcategoria: "Resíduos de Natureza Orgânica e Agropastoril Crus", codigo_ibama: "02 01 99", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Cinza de caldeira de biomassa", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "03 03 07", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Casca de madeira suja", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "03 01 06", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos de madeira e papel", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "03 99 99", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Fosfogesso", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "06 01 06", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Cinza volante de termelétrica", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "10 02 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Cinza pesada de termelétrica", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "10 02 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Gesso de dessulfuração - FGD", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "10 02 03", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Finos de coque", grupo: 3, categoria_subcategoria: "Massa Industrial de Processos Térmicos e Celulose", codigo_ibama: "10 01 05", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Aparas de couro acabado", grupo: 3, categoria_subcategoria: "Indústria Coureiro-Têxtil de Baixo Risco", codigo_ibama: "04 01 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos de couro e têxtil", grupo: 3, categoria_subcategoria: "Indústria Coureiro-Têxtil de Baixo Risco", codigo_ibama: "04 99 99", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Madeira limpa de obra", grupo: 3, categoria_subcategoria: "Construção Civil Biodegradável ou Solúvel", codigo_ibama: "17 02 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Papelão de obra", grupo: 3, categoria_subcategoria: "Construção Civil Biodegradável ou Solúvel", codigo_ibama: "17 02 03", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Gesso acartonado - drywall", grupo: 3,  categoria_subcategoria: "Construção Civil Biodegradável ou Solúvel", codigo_ibama: "17 03 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Placa de gesso comum", grupo: 3,  categoria_subcategoria: "Construção Civil Biodegradável ou Solúvel", codigo_ibama: "17 03 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos de construção", grupo: 3,  categoria_subcategoria: "Construção Civil Biodegradável ou Solúvel", codigo_ibama: "17 99 99", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Lodo de ETE sanitária", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 01 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Lodo de ETE industrial orgânico", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 01 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Lodo de ETA - Estação de Tratamento de Água", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 01 03", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Lodo de caixa de gordura", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 01 04", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Escuma e areia de desarenador", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 03 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos de gradeamento", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 03 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos de saneamento", grupo: 3, categoria_subcategoria: "Saneamento e Tratamento Biológico (Efluentes)", codigo_ibama: "19 99 99", classe_perigo_nbr: "Classe II-A" },
  
  { termo_amigavel: "Equipamentos de informática obsoletos", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "16 02 04", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Lâmpadas LED", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "16 04 03", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos não especificados", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "16 99 99", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos de varrição e feiras", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "20 06 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos de poda urbana", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "20 06 02", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos têxteis de coleta seletiva", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "20 07 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Resíduos volumosos - móveis/colchões", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "20 08 01", classe_perigo_nbr: "Classe II-A" },
  { termo_amigavel: "Outros resíduos urbanos", grupo: 3, categoria_subcategoria: "Logística Reversa e Triagem Urbana Complexa", codigo_ibama: "20 99 99", classe_perigo_nbr: "Classe II-A" },

  // --- GRUPO 4 ---
  { termo_amigavel: "Rejeito de bauxita / lama vermelha", grupo: 4, categoria_subcategoria: "Mineração com Presença de Agentes Químicos Pesados", codigo_ibama: "01 03 06", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Rejeito de ouro cianetado", grupo: 4, categoria_subcategoria: "Mineração com Presença de Agentes Químicos Pesados", codigo_ibama: "01 01 07", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Rejeito de carvão mineral", grupo: 4, categoria_subcategoria: "Mineração com Presença de Agentes Químicos Pesados", codigo_ibama: "01 01 09", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Rejeito de chumbo/zinco", grupo: 4, categoria_subcategoria: "Mineração com Presença de Agentes Químicos Pesados", codigo_ibama: "01 01 13", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Madeira tratada com CCA/creosoto", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "MDF/MDP com presença de formol", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Licor negro", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Licor verde", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Dregs - borra de cal", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Grits areia de cal", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lama de cal", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo biológico de ETE de celulose", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 06", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Rejeito de fibra curta", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 08", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo de destintamento", grupo: 4, categoria_subcategoria: "Madeira e Papel com Tratamento Químico / Celulose Corrosiva", codigo_ibama: "03 03 09", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Aparas de couro wet-blue", grupo: 4, categoria_subcategoria: "Indústria do Couro e Têxtil (Química Pesada)", codigo_ibama: "04 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Pó de lixadeira de couro", grupo: 4, categoria_subcategoria: "Indústria do Couro e Têxtil (Química Pesada)", codigo_ibama: "04 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo de tingimento têxtil", grupo: 4, categoria_subcategoria: "Indústria do Couro e Têxtil (Química Pesada)", codigo_ibama: "04 02 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Banho de corante exaurido", grupo: 4, categoria_subcategoria: "Indústria do Couro e Têxtil (Química Pesada)", codigo_ibama: "04 02 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Borra de petróleo", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Catalisador FCC gasto", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Coque de petróleo fino", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Borra ácida", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Emulsão oleosa de refinaria", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos de refino", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "05 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Óleo lubrificante usado - OLUC", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "13 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Emulsão oleosa industrial", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "13 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Filtro de óleo usado", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "13 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Borra de óleo industrial", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "13 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros óleos usados", grupo: 4, categoria_subcategoria: "Cadeia Petroquímica, Refino e Óleos Minerais Usados", codigo_ibama: "13 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Ácido sulfúrico exaurido", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Ácido clorídrico exaurido", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Ácido fluorídrico exaurido", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Soda cáustica exaurida", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo de fosfatização", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Fosfato bicálcico fora de especificação", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 08", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Cloreto de potássio contaminado", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 09", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Ureia fora de especificação", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 10", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Sulfato de amônio industrial", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 11", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Nitrato de amônio industrial", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 12", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Cinza de caldeira de carvão mineral", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 01 14", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos químicos inorgânicos", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "06 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Solventes halogenados usados", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Solventes não halogenados usados", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Thinner sujo", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resinas epóxi vencidas", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resinas poliéster vencidas", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Carvão ativado industrial exaurido", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 11", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Sílica gel industrial usada", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 12", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Alumina ativada exaurida", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 13", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Peneira molecular saturada", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 14", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Diatomita usada em filtração", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 01 15", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos químicos orgânicos", grupo: 4, categoria_subcategoria: "Processos Químicos Inorgânicos e Orgânicos Totais", codigo_ibama: "07 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Tinta à base de solvente usada", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Borra de tinta", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Verniz vencido", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduos de adesivos", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo de cabine de pintura", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos de tintas e vernizes", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "08 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Revelador usado", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "09 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Fixador usado", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "09 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos fotográficos", grupo: 4, categoria_subcategoria: "Setores de Acabamento (Tintas, Vernizes, Adesivos e Fotografia)", codigo_ibama: "09 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Pó de balão de alto-forno", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "10 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo de FGD", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "10 02 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos de processos térmicos", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "10 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo galvânico de cromo", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo galvânico de níquel", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lodo galvânico de zinco", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Banho de cianeto exaurido", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Água de lavagem ácida", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos de tratamento de superfície", grupo: 4, categoria_subcategoria: "Processos Térmicos Pesados e Galvanoplastia", codigo_ibama: "11 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Embalagem de agrotóxico tríplice lavada", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Embalagem de agrotóxico contaminada", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Big bag usado sujo", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "IBC 1000L com resíduos", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 06", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Tambor metálico 200L usado", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 07", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Tambor plástico 200L usado", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 01 08", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Filtro de manga usado", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 02 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Carvão ativado de filtração ambiental exaurido", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 02 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Estopa contaminada com óleo/solvente", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 02 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Absorventes industriais usados", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 02 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outras embalagens e absorventes contaminados", grupo: 4, categoria_subcategoria: "Logística Reversa de Embalagens Contaminadas e Absorventes Industriais", codigo_ibama: "15 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Catalisador automotivo exaurido", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Placas de circuito impresso", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 02 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Fontes de alimentação com metais pesados", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 02 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Baterias chumbo-ácidas", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 03 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Pilhas alcalinas/botão/lítio", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 03 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lâmpadas fluorescentes", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 04 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lâmpadas de vapor de mercúrio/sódio", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 04 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Medicamentos vencidos domiciliares", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 05 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Medicamentos vencidos hospitalares", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "16 05 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Eletrônicos domésticos", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Eletrônicos linha branca", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Eletrônicos linha verde - TI", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Eletrônicos linha azul", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Cartuchos e toners", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Pilhas e baterias portáteis", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 02 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduos de lâmpadas mistas", grupo: 4, categoria_subcategoria: "Equipamentos Inservíveis com Componentes Tóxicos e Iluminação", codigo_ibama: "20 03 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Lã de vidro/rocha de demolição", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 03 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Amianto friável", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 04 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Amianto não friável - telhas/caixas d'água", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 04 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Tintas e solventes de obra", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 04 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Verniz e selador vencido", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 04 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lata de tinta com resíduo seco ou líquido", grupo: 4, categoria_subcategoria: "Construção Civil Contaminada (RCC Classe C e D)", codigo_ibama: "17 04 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  
  { termo_amigavel: "Resíduo infectante - Grupo A", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduo químico hospitalar - Grupo B", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Perfurocortante - Grupo E", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 03", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Medicamento vencido hospitalar", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 04", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Quimioterápico vencido", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 05", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Amálgama dentária residual", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 01 06", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Outros resíduos de saúde", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "18 99 99", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Lixiviado de aterro - chorume", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "19 02 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Salmoura industrial", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "19 02 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduos portuários", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "20 05 01", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduos aeroportuários", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "20 05 02", classe_perigo_nbr: "Classe I (Perigoso)" },
  { termo_amigavel: "Resíduos ferroviários", grupo: 4, categoria_subcategoria: "Serviços de Saúde (RSS) e Saneamento Crítico", codigo_ibama: "20 05 03", classe_perigo_nbr: "Classe I (Perigoso)" }
];
