-- RODE ESTE SCRIPT NO SQL EDITOR DO SUPABASE PARA RESOLVER O ERRO DE CONSTRAINT DA CLASSE
-- ELE REMOVE A VALIDAÇÃO RÍGIDA DO BANCO DE DADOS, PERMITINDO QUE O FORMULÁRIO ENVIE AS INFORMAÇÕES CORRETAMENTE

ALTER TABLE anuncios DROP CONSTRAINT IF EXISTS anuncios_classe_check;
