-- RODE ESTE SCRIPT NO SQL EDITOR DO SUPABASE PARA RESOLVER ERROS DE VALIDAÇÃO DE CADASTROS E PLANOS
-- ELE REMOVE AS VALIDAÇÕES RÍGIDAS (CONSTRAINTS CHECK) DA TABELA DE CADASTROS, PERMITINDO QUE O ADMIN SALVE QUALQUER STATUS E PLANO

ALTER TABLE cadastros DROP CONSTRAINT IF EXISTS cadastros_nivel_selo_check;
ALTER TABLE cadastros DROP CONSTRAINT IF EXISTS cadastros_plano_check;
ALTER TABLE cadastros DROP CONSTRAINT IF EXISTS cadastros_status_documentos_check;
ALTER TABLE cadastros DROP CONSTRAINT IF EXISTS cadastros_tipo_parte_check;
ALTER TABLE cadastros DROP CONSTRAINT IF EXISTS cadastros_subtipo_check;
