-- RODE ESTE SCRIPT NO SQL EDITOR DO SUPABASE PARA ATUALIZAR AS TABELAS CONFORME A SEÇÃO 10 DO MANUAL
ALTER TABLE cadastros
ADD COLUMN IF NOT EXISTS licencas TEXT,
ADD COLUMN IF NOT EXISTS licenca_url TEXT,
ADD COLUMN IF NOT EXISTS pontuacao_legal INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS nota_operacao_0a100 INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS selo_metal TEXT CHECK (selo_metal IN ('Bronze', 'Prata', 'Ouro', 'Sem')) DEFAULT 'Sem',
ADD COLUMN IF NOT EXISTS audit_trail_privado TEXT,
ADD COLUMN IF NOT EXISTS is_transportadora_propria BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS tipo_plano TEXT DEFAULT 'Free',
ADD COLUMN IF NOT EXISTS plano_vencimento DATE,
ADD COLUMN IF NOT EXISTS publicacoes_usadas INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_url TEXT;
