-- RODE ESTE SCRIPT NO EDITOR SQL DO SUPABASE PARA ADICIONAR AS COLUNAS DO BLOCO 1
ALTER TABLE anuncios
ADD COLUMN IF NOT EXISTS grupo INTEGER,
ADD COLUMN IF NOT EXISTS categoria_subcategoria TEXT,
ADD COLUMN IF NOT EXISTS nome_material TEXT,
ADD COLUMN IF NOT EXISTS distancia_km INTEGER,
ADD COLUMN IF NOT EXISTS tipo_fluxo TEXT,
ADD COLUMN IF NOT EXISTS regime_fornecimento TEXT,
ADD COLUMN IF NOT EXISTS volume_total NUMERIC,
ADD COLUMN IF NOT EXISTS aceita_menor_valor BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS preco_unidade NUMERIC DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS situacao_anuncio TEXT DEFAULT 'NORMAL',
ADD COLUMN IF NOT EXISTS selo_minimo TEXT DEFAULT 'LIVRE',
ADD COLUMN IF NOT EXISTS tem_avaliacao BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS responsavel_frete BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS infraestrutura_minima TEXT[],
ADD COLUMN IF NOT EXISTS origem_processo_gerador TEXT,
ADD COLUMN IF NOT EXISTS especificacoes_tecnicas_exigencias TEXT,
ADD COLUMN IF NOT EXISTS requisitos_adicionais_observacoes TEXT;
